apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-multi-pod
  labels:
    app  : my-k8s-application
    env  : prod
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cia
  template:
    metadata:
      labels:
        project: cia
    spec:
      containers:
        - name: my-web
          image: adv4000/k8sphp:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

        - name: not-my-web
          image: tomcat:8.5.38
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-multi-pods-service
  labels:
    env  : prod
    owner: SamsonovEvgeny 
spec:
  type: LoadBalancer
  selector:
    project: cia
  ports:
  - name      : my-web-app-listener
    protocol  : TCP
    port      : 80
    targetPort: 80

  - name      : not-my-web-app-listener
    protocol  : TCP
    port      : 8888
    targetPort: 8080  
  
